register:
  path: /register
  controller: App\Controller\AuthController::register
  methods: POST

api_login_check:
  path: /api/login_check

api_logout:
  path: /logout

api:
  path: /api
  controller: App\Controller\AuthController::api
